#!/usr/bin/env bash
# run_u4.sh — U-4 harness. Runs inside the Ubuntu 24.04 container.
#   1. obtain a freestanding mbedTLS SOURCE tree (release tarball, cached)
#   2. build the freestanding self-contained archive (make freestanding-lib-selfcontained)
#   3. build BOOTX64.EFI (build_u4.sh)
#   4. build a FAT ESP image with EFI/BOOT/BOOTX64.EFI + startup.nsh
#   5. start a TLS responder (openssl s_server -www) on the host; guest reaches it at 10.0.2.2:PORT
#   6. boot QEMU x86_64 + OVMF (TCG, no KVM), e1000 NIC, SLIRP user-net, serial to stdout
#   7. capture serial, grep for U-4: markers / the status line / HTTP/1
#
# Env:
#   KEEL_ROOT     repo root (default: ../..)
#   TARGET_PORT   host TLS responder port (default 18443)
#   MBEDTLS_VER   mbedTLS release version (default 3.6.2)
#   OVMF_CODE / OVMF_VARS   override OVMF fds
#   BOOT_TIMEOUT  qemu timeout seconds (default 240 — TLS handshake under TCG is slow)
set -uo pipefail
cd "$(dirname "$0")"

: "${KEEL_ROOT:=../..}"
TARGET_PORT="${TARGET_PORT:-18443}"
BOOT_TIMEOUT="${BOOT_TIMEOUT:-240}"
MBEDTLS_VER="${MBEDTLS_VER:-3.6.2}"
export TARGET_PORT

echo "=== U-4 run harness (HTTPS over EFI_TCP4 + freestanding mbedTLS) ==="

# ---- 1. mbedTLS release tarball (source tree only; we compile it ourselves) ----
CACHE="${MBEDTLS_CACHE:-/tmp/mbedtls_cache}"
mkdir -p "$CACHE"
MBEDTLS_SRC="$CACHE/mbedtls-$MBEDTLS_VER"
if [ ! -d "$MBEDTLS_SRC/library" ]; then
  TARBALL="$CACHE/mbedtls-$MBEDTLS_VER.tar.bz2"
  URL="https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-$MBEDTLS_VER/mbedtls-$MBEDTLS_VER.tar.bz2"
  echo "downloading mbedTLS $MBEDTLS_VER release tarball ..."
  curl -fsSL -o "$TARBALL" "$URL" || { echo "mbedTLS download FAILED ($URL)"; exit 2; }
  echo "extracting ..."
  tar -xf "$TARBALL" -C "$CACHE" || { echo "mbedTLS extract FAILED"; exit 2; }
fi
[ -d "$MBEDTLS_SRC/library" ] || { echo "ERROR: $MBEDTLS_SRC/library missing after extract"; exit 2; }
export MBEDTLS_SRC
echo "mbedTLS source: $MBEDTLS_SRC"

# ---- 2. freestanding self-contained archive (x86_64), COFF-aware nm/ar ----
pick() { for c in "$@"; do command -v "$c" >/dev/null 2>&1 && { echo "$c"; return; }; done; }
LLVM_NM="$(pick llvm-nm llvm-nm-18 llvm-nm-17 llvm-nm-16)"
LLVM_AR="$(pick llvm-ar llvm-ar-18 llvm-ar-17 llvm-ar-16)"
ARCHIVE_ARGS=()
[ -n "$LLVM_NM" ] && ARCHIVE_ARGS+=( "NM=$LLVM_NM" )
[ -n "$LLVM_AR" ] && ARCHIVE_ARGS+=( "AR=$LLVM_AR" )
echo "building libkeel_freestanding_selfcontained.a (${ARCHIVE_ARGS[*]:-default tools}) ..."
( cd "$KEEL_ROOT" && make freestanding-lib-selfcontained "${ARCHIVE_ARGS[@]}" ) \
  || { echo "ARCHIVE BUILD FAILED"; exit 2; }

# ---- 2b. production TLS: generate the responder cert (dNSName SAN) + embed it as the
# CA the client verifies against, BEFORE the build (build_u4.sh embeds u4_ca_embed.h).
# Also force real EFI_RNG (virtio-rng). Default (spike) skips this entirely. ----
PROD_HOST="${KL_U4_PROD_HOST:-server.keel.test}"
PRODDIR="$(pwd)/u4_prod_cert"
if [ "${U4_MODE:-spike}" = "prod" ]; then
  export U4_VIRTIO_RNG=1
  mkdir -p "$PRODDIR"
  # U4_CERT=expired (U-8 negative test): mint the responder cert in the PAST via faketime so
  # it is already expired. With cert validity-time enforcement live, the client MUST reject it
  # (CERT_EXPIRED) — i.e. NO 200. U4_CERT=valid (default) mints a currently-valid cert (→ 200).
  # GENPFX is an ARRAY so the faketime timestamp (which contains a space) stays a single
  # argument; empty in the valid case (expands to nothing).
  GENPFX=()
  if [ "${U4_CERT:-valid}" = "expired" ]; then
    command -v faketime >/dev/null || { echo "U4_CERT=expired needs faketime (apt install faketime)"; exit 2; }
    GENPFX=(faketime -f '2020-01-01 00:00:00')   # faketime format: 'YYYY-MM-DD HH:MM:SS'
    echo "prod: minting an EXPIRED cert (valid 2020-01-01..02) to test cert-time enforcement"
  fi
  "${GENPFX[@]}" openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$PRODDIR/k.pem" -out "$PRODDIR/c.pem" \
    -subj "/CN=$PROD_HOST" -addext "subjectAltName=DNS:$PROD_HOST" -days 2 >/dev/null 2>&1 \
    || { echo "prod cert gen FAILED"; exit 2; }
  python3 - "$PRODDIR/c.pem" > u4_ca_embed.h <<'PY'
import sys
data = open(sys.argv[1], "rb").read()
print("/* generated by run_u4.sh (U4_MODE=prod) — do not edit */")
print("#ifndef U4_CA_EMBED_H\n#define U4_CA_EMBED_H\n#include <stddef.h>")
print("static const unsigned char g_u4_ca_pem[] = {" + ",".join(str(b) for b in data) + ",0};")
print("static const size_t g_u4_ca_pem_len = sizeof(g_u4_ca_pem);")
print("#endif")
PY
  echo "prod: cert CN/SAN=$PROD_HOST embedded as CA -> u4_ca_embed.h"
fi

# ---- 3. build the EFI app ----
TARGET_PORT="$TARGET_PORT" MBEDTLS_SRC="$MBEDTLS_SRC" U4_MODE="${U4_MODE:-spike}" \
  KL_U4_PROD_HOST="$PROD_HOST" ./build_u4.sh || { echo "BUILD FAILED"; exit 2; }

# ---- 4. ESP FAT image ----
ESP=esp.img
rm -f "$ESP"
dd if=/dev/zero of="$ESP" bs=1M count=64 status=none
mformat -i "$ESP" -F ::
mmd    -i "$ESP" ::/EFI
mmd    -i "$ESP" ::/EFI/BOOT
mcopy  -i "$ESP" BOOTX64.EFI ::/EFI/BOOT/BOOTX64.EFI
mcopy  -i "$ESP" startup.nsh ::/startup.nsh
echo "ESP image built:"
mdir -i "$ESP" ::/EFI/BOOT/

# ---- 5. host TLS responder: a Python TLS server sending a Content-Length'd HTTP/1.1
# 200. NOTE: openssl s_server -www replies HTTP/1.0 with NO Content-Length (body
# delimited by connection close). KEEL's async client + mbedTLS adapter surface a TLS
# EOF/close_notify as tls_read()==-1, which async_handle_receiving treats as KL_ERR_IO
# — so a close-delimited HTTPS body is dropped even though it fully arrived (a general
# Keel client+TLS-adapter interaction, NOT EFI-specific; the U-4 diag proves the whole
# encrypted response is received + decrypted over EFI_TCP4). Real servers send
# Content-Length, so the parser completes on the body BEFORE EOF and the client
# succeeds. This responder does exactly that. ----
if [ "${U4_MODE:-spike}" = "prod" ]; then
  CERTDIR="$PRODDIR"        # reuse the embedded (CA-verified) cert/key
else
  CERTDIR="$(mktemp -d)"
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$CERTDIR/k.pem" -out "$CERTDIR/c.pem" \
    -subj "/CN=test" -days 1 >/dev/null 2>&1 || { echo "openssl cert gen FAILED"; exit 2; }
fi
cat > "$CERTDIR/tlsd.py" <<'PY'
import ssl, socket, sys, threading
port = int(sys.argv[1]); cert = sys.argv[2]; key = sys.argv[3]
body = b"U-4 KlHttpClient HTTPS responder OK\n"
resp = (b"HTTP/1.1 200 OK\r\nContent-Length: %d\r\nConnection: close\r\n\r\n" % len(body)) + body
ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
ctx.load_cert_chain(cert, key)
srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
srv.bind(("0.0.0.0", port)); srv.listen(16)
print("python TLS responder on 0.0.0.0:%d (HTTP/1.1 + Content-Length)" % port, flush=True)
def serve(raw):
    try:
        s = ctx.wrap_socket(raw, server_side=True)
        s.recv(8192)                 # consume the request
        s.sendall(resp)
        try: s.unwrap()              # send close_notify then FIN
        except Exception: pass
    except Exception:
        pass
    finally:
        try: raw.close()
        except Exception: pass
while True:
    c, _ = srv.accept()
    threading.Thread(target=serve, args=(c,), daemon=True).start()
PY
# U4_RESPONDER=close uses openssl s_server -www: HTTP/1.0, NO Content-Length (body
# delimited by connection close) — the regression case for the close-delimited HTTPS
# fix (KlTls.at_eof). Default (clen) = the Python Content-Length responder above.
if [ "${U4_RESPONDER:-clen}" = "close" ]; then
  echo "starting CLOSE-DELIMITED responder (openssl s_server -www, HTTP/1.0 no Content-Length) ..."
  openssl s_server -accept "$TARGET_PORT" -cert "$CERTDIR/c.pem" -key "$CERTDIR/k.pem" \
    -www -quiet -naccept 20 >/tmp/tlsd_u4.log 2>&1 &
  SS_PID=$!
else
  echo "starting python TLS responder on 0.0.0.0:$TARGET_PORT ..."
  python3 "$CERTDIR/tlsd.py" "$TARGET_PORT" "$CERTDIR/c.pem" "$CERTDIR/k.pem" >/tmp/tlsd_u4.log 2>&1 &
  SS_PID=$!
fi
sleep 1
cat /tmp/tlsd_u4.log 2>/dev/null || true
echo "python TLS responder pid=$SS_PID on 0.0.0.0:$TARGET_PORT"
# sanity: can the host itself reach it over TLS?
echo -e "GET / HTTP/1.1\r\nHost: t\r\nConnection: close\r\n\r\n" | \
  openssl s_client -connect "127.0.0.1:$TARGET_PORT" -quiet 2>/dev/null | head -1 || true
cleanup() { kill "$SS_PID" 2>/dev/null || true; rm -rf "$CERTDIR"; }
trap cleanup EXIT

# ---- 6. locate OVMF ----
find_ovmf() {
  for c in "${OVMF_CODE:-}" \
    /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/ovmf/OVMF.fd ; do
    [ -n "$c" ] && [ -f "$c" ] && { echo "$c"; return; }
  done
}
find_vars() {
  for v in "${OVMF_VARS:-}" \
    /usr/share/OVMF/OVMF_VARS_4M.fd /usr/share/OVMF/OVMF_VARS.fd ; do
    [ -n "$v" ] && [ -f "$v" ] && { echo "$v"; return; }
  done
}
OVMF_CODE_FD="$(find_ovmf)"
OVMF_VARS_FD="$(find_vars)"
if [ -z "$OVMF_CODE_FD" ]; then echo "ERROR: no OVMF code fd found"; exit 3; fi
echo "OVMF code: $OVMF_CODE_FD"
echo "OVMF vars: ${OVMF_VARS_FD:-<none>}"
VARS_RW=vars_rw.fd
if [ -n "$OVMF_VARS_FD" ]; then cp "$OVMF_VARS_FD" "$VARS_RW"; fi

# ---- 7. boot QEMU (TCG; no KVM in container) ----
QEMU_ARGS=(
  -machine q35
  -m 512
  -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE_FD"
)
[ -n "$OVMF_VARS_FD" ] && QEMU_ARGS+=( -drive if=pflash,format=raw,file="$VARS_RW" )
QEMU_ARGS+=(
  -drive format=raw,file="$ESP"
  -netdev "user,id=n0"
  -device e1000,netdev=n0
  -serial stdio
  -display none
  -monitor none
  -no-reboot
)
# U4_VIRTIO_RNG=1 adds a virtio-rng device so OVMF's VirtioRngDxe publishes
# EFI_RNG_PROTOCOL — required by the production TLS mode (real entropy, no weak
# fallback). Default off keeps the plain spike run unchanged.
if [ "${U4_VIRTIO_RNG:-0}" = "1" ]; then
  QEMU_ARGS+=( -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0 )
fi
# U4_CLOCK=bad (U-8 negative test): set the emulated RTC to the year 2000 so OVMF GetTime
# returns a year below KL_UEFI_TIME_FLOOR_YEAR. The clock gate must then REFUSE TLS init —
# no handshake, no 200 — even with a currently-VALID cert, proving fail-closed is structural
# (not merely epoch-0-vs-cert-dates). Default keeps the host clock.
if [ "${U4_CLOCK:-host}" = "bad" ]; then
  QEMU_ARGS+=( -rtc "base=2000-01-01T00:00:00" )
  echo "U4_CLOCK=bad: emulated RTC set to 2000 (below the trust floor) — TLS must refuse"
fi

echo "=== qemu cmd ==="
echo "timeout ${BOOT_TIMEOUT} qemu-system-x86_64 ${QEMU_ARGS[*]}"
echo "=== serial output begin ==="
timeout "${BOOT_TIMEOUT}" qemu-system-x86_64 "${QEMU_ARGS[@]}" 2>&1 | tee /tmp/serial_u4.log
echo "=== serial output end ==="

echo "=== grep markers ==="
grep -E 'U-4:|HTTP/1\.[01]' /tmp/serial_u4.log || echo "(no U-4 markers found)"
echo "=== s_server log tail ==="
tail -5 /tmp/sserver_u4.log 2>/dev/null || true
