#!/usr/bin/env bash
# run_s6.sh — S-6 harness (HTTPS server over EFI_TCP4 + freestanding mbedTLS). Runs
# inside the Ubuntu 24.04 container. The server mirror of run_u4.sh:
#   1. obtain a freestanding mbedTLS SOURCE tree (release tarball, cached)
#   2. build the freestanding self-contained SERVER archive
#   3. generate a self-signed server cert+key and embed it -> s6_cert_embed.h
#   4. build BOOTX64.EFI (build_s6.sh)
#   5. FAT ESP image (EFI/BOOT/BOOTX64.EFI + startup.nsh)
#   6. boot QEMU x86_64 + OVMF (TCG), e1000 NIC, SLIRP with hostfwd :443 -> host, in the
#      background; wait for "S-6: listening on :443"
#   7. curl -k https://127.0.0.1:HOST_PORT/ ; expect 200 + the "S-6: GO" serial marker
#
# The server presents a self-signed cert, so the host curl uses -k (this test exercises
# the SERVER's TLS, not client CA verification). Entropy uses the INSECURE weak fallback
# (build_s6.sh default), so no virtio-rng device is needed.
#
# Env:
#   KEEL_ROOT     repo root (default: ../..)
#   HOST_PORT     host side of the :443 forward (default 18443)
#   MBEDTLS_VER   mbedTLS release version (default 3.6.2)
#   OVMF_CODE / OVMF_VARS   override OVMF fds
#   BOOT_TIMEOUT  qemu timeout seconds (default 300 — TLS handshake under TCG is slow)
set -uo pipefail
cd "$(dirname "$0")"

: "${KEEL_ROOT:=../..}"
HOST_PORT="${HOST_PORT:-18443}"
BOOT_TIMEOUT="${BOOT_TIMEOUT:-300}"
MBEDTLS_VER="${MBEDTLS_VER:-3.6.2}"

echo "=== S-6 run harness (HTTPS server over EFI_TCP4 + freestanding mbedTLS) ==="

# ---- 1. mbedTLS release tarball (source tree only; compiled freestanding by build_s6) ----
CACHE="${MBEDTLS_CACHE:-/tmp/mbedtls_cache}"
mkdir -p "$CACHE"
MBEDTLS_SRC="$CACHE/mbedtls-$MBEDTLS_VER"
if [ ! -d "$MBEDTLS_SRC/library" ]; then
  TARBALL="$CACHE/mbedtls-$MBEDTLS_VER.tar.bz2"
  URL="https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-$MBEDTLS_VER/mbedtls-$MBEDTLS_VER.tar.bz2"
  echo "downloading mbedTLS $MBEDTLS_VER ..."
  curl -fsSL -o "$TARBALL" "$URL" || { echo "mbedTLS download FAILED ($URL)"; exit 2; }
  tar -xf "$TARBALL" -C "$CACHE" || { echo "mbedTLS extract FAILED"; exit 2; }
fi
[ -d "$MBEDTLS_SRC/library" ] || { echo "ERROR: $MBEDTLS_SRC/library missing"; exit 2; }
export MBEDTLS_SRC
echo "mbedTLS source: $MBEDTLS_SRC"

# ---- 2. freestanding self-contained SERVER archive (x86_64), COFF-aware nm/ar ----
pick() { for c in "$@"; do command -v "$c" >/dev/null 2>&1 && { echo "$c"; return; }; done; }
LLVM_NM="$(pick llvm-nm llvm-nm-18 llvm-nm-17 llvm-nm-16)"
LLVM_AR="$(pick llvm-ar llvm-ar-18 llvm-ar-17 llvm-ar-16)"
ARCHIVE_ARGS=()
[ -n "$LLVM_NM" ] && ARCHIVE_ARGS+=( "NM=$LLVM_NM" )
[ -n "$LLVM_AR" ] && ARCHIVE_ARGS+=( "AR=$LLVM_AR" )
echo "building libkeel_freestanding_server_selfcontained.a ..."
( cd "$KEEL_ROOT" && make freestanding-lib-server-selfcontained "${ARCHIVE_ARGS[@]}" ) \
  || { echo "ARCHIVE BUILD FAILED"; exit 2; }

# ---- 3. self-signed server cert + key, embedded as s6_cert_embed.h ----
CERTDIR="$(mktemp -d)"
openssl req -x509 -newkey rsa:2048 -nodes \
  -keyout "$CERTDIR/key.pem" -out "$CERTDIR/cert.pem" \
  -subj "/CN=keel.uefi.test" -addext "subjectAltName=DNS:keel.uefi.test,IP:10.0.2.15" \
  -days 2 >/dev/null 2>&1 || { echo "server cert gen FAILED"; exit 2; }
python3 - "$CERTDIR/cert.pem" "$CERTDIR/key.pem" > s6_cert_embed.h <<'PY'
import sys
cert = open(sys.argv[1], "rb").read()
key  = open(sys.argv[2], "rb").read()
def emit(name, data):
    print("static const unsigned char %s[] = {%s,0};" % (name, ",".join(str(b) for b in data)))
    print("static const size_t %s_len = sizeof(%s);" % (name, name))   # includes trailing NUL (PEM)
print("/* generated by run_s6.sh — do not edit */")
print("#ifndef S6_CERT_EMBED_H\n#define S6_CERT_EMBED_H\n#include <stddef.h>")
emit("g_s6_cert_pem", cert)
emit("g_s6_key_pem", key)
print("#endif")
PY
echo "embedded self-signed server cert -> s6_cert_embed.h (CN=keel.uefi.test)"

# ---- 4. build the EFI app ----
MBEDTLS_SRC="$MBEDTLS_SRC" ./build_s6.sh || { echo "BUILD FAILED"; exit 2; }

# ---- 5. ESP FAT image ----
ESP=esp_s6.img
rm -f "$ESP"
dd if=/dev/zero of="$ESP" bs=1M count=64 status=none
mformat -i "$ESP" -F ::
mmd   -i "$ESP" ::/EFI
mmd   -i "$ESP" ::/EFI/BOOT
mcopy -i "$ESP" BOOTX64.EFI ::/EFI/BOOT/BOOTX64.EFI
mcopy -i "$ESP" startup.nsh ::/startup.nsh
echo "ESP image built:"; mdir -i "$ESP" ::/EFI/BOOT/

# ---- 6. locate OVMF ----
find_one() { for c in "$@"; do [ -n "$c" ] && [ -f "$c" ] && { echo "$c"; return; }; done; }
OVMF_CODE_FD="$(find_one "${OVMF_CODE:-}" /usr/share/OVMF/OVMF_CODE_4M.fd /usr/share/OVMF/OVMF_CODE.fd /usr/share/ovmf/OVMF.fd)"
OVMF_VARS_FD="$(find_one "${OVMF_VARS:-}" /usr/share/OVMF/OVMF_VARS_4M.fd /usr/share/OVMF/OVMF_VARS.fd)"
[ -z "$OVMF_CODE_FD" ] && { echo "ERROR: no OVMF code fd found"; exit 3; }
echo "OVMF code: $OVMF_CODE_FD"; echo "OVMF vars: ${OVMF_VARS_FD:-<none>}"
VARS_RW=vars_rw_s6.fd
[ -n "$OVMF_VARS_FD" ] && cp "$OVMF_VARS_FD" "$VARS_RW"

# ---- 7. boot QEMU (TCG), serial -> log, in the background; then curl the forward ----
SERIAL=/tmp/serial_s6.log
rm -f "$SERIAL"
QEMU_ARGS=( -machine q35 -m 512
  -drive if=pflash,format=raw,readonly=on,file="$OVMF_CODE_FD" )
[ -n "$OVMF_VARS_FD" ] && QEMU_ARGS+=( -drive if=pflash,format=raw,file="$VARS_RW" )
QEMU_ARGS+=( -drive format=raw,file="$ESP"
  -netdev "user,id=n0,hostfwd=tcp::${HOST_PORT}-:443"
  -device e1000,netdev=n0
  -serial file:"$SERIAL" -display none -monitor none -no-reboot )
echo "=== qemu cmd ==="; echo "qemu-system-x86_64 ${QEMU_ARGS[*]}"
timeout "${BOOT_TIMEOUT}" qemu-system-x86_64 "${QEMU_ARGS[@]}" &
QEMU_PID=$!
cleanup() { kill "$QEMU_PID" 2>/dev/null || true; rm -rf "$CERTDIR"; }
trap cleanup EXIT

echo "waiting for 'S-6: listening on :443' (up to ${BOOT_TIMEOUT}s) ..."
listening=0
for _ in $(seq 1 "${BOOT_TIMEOUT}"); do
  if ! kill -0 "$QEMU_PID" 2>/dev/null; then echo "qemu exited early"; break; fi
  if grep -q "S-6: listening on :443" "$SERIAL" 2>/dev/null; then listening=1; break; fi
  sleep 1
done

status=""
if [ "$listening" = 1 ]; then
  echo "guest is listening; curling https://127.0.0.1:${HOST_PORT}/ (-k, self-signed) ..."
  for _ in $(seq 1 30); do
    status="$(curl -sk -o /tmp/s6_body.txt -w '%{http_code}' --max-time 8 \
                "https://127.0.0.1:${HOST_PORT}/" 2>/dev/null || true)"
    [ "$status" = "200" ] && break
    sleep 1
  done
  echo "curl HTTPS status = ${status:-<none>}"
  echo "--- response body ---"; cat /tmp/s6_body.txt 2>/dev/null; echo "--- end ---"
else
  echo "guest never reported 'listening'"
fi

sleep 2
echo "=== serial markers ==="
grep -E 'S-6:' "$SERIAL" 2>/dev/null || echo "(no S-6 markers found)"

if [ "$status" = "200" ] && grep -q "S-6: GO" "$SERIAL" 2>/dev/null; then
  echo "S-6: PASS — HTTPS server served GET / -> 200 over EFI_TCP4 + mbedTLS"
  exit 0
fi
echo "S-6: FAIL (status=${status:-<none>}, GO marker $(grep -q 'S-6: GO' "$SERIAL" 2>/dev/null && echo present || echo absent))"
echo "=== serial tail ==="; tail -40 "$SERIAL" 2>/dev/null || true
exit 1
