/*
 * http_redirect.c: HTTP redirect following (sync + async)
 *
 * Wraps kl_http_client_request / kl_http_client_start with automatic 3xx
 * redirect following. Method transformation per RFC 7231/7538.
 * Does not modify the HTTP client.
 */

#include <keel/http_redirect.h>
#include "../../allocator_validate.h"
#include "kl_cstr.h"   /* kl_ascii_strn?casecmp: ASCII, locale-free, portable */

#include <string.h>

/* ── Internal struct ─────────────────────────────────────────────── */

struct KlHttpRedirectClient {
    KlHttpClient          *inner;          /* current in-flight async client */
    KlAllocator       *alloc;
    KlEventCtx        *ev_ctx;
    /* The caller's config, COPIED at start: every hop after the first starts
     * from a later event-loop turn, when a config the caller kept on its stack
     * is gone. (Members it points at - tls, decompress, proxy, sockets - are
     * the caller's to keep alive, as for any client.) NULL when none given. */
    KlHttpClientConfig     cfg_copy;
    const KlHttpClientConfig *cfg;
    KlHttpClientPool      *pool;           /* NULL if not pooled */

    /* Original request (heap-copied for async lifetime) */
    KlHttpClientHeader    *headers;        /* deep-copied array */
    int                num_headers;
    char              *body;           /* copied body (NULL if none) */
    size_t             body_len;

    /* Redirect state */
    int                max_redirects;
    KlHttpRedirectCheckFn on_redirect;    /* per-hop policy (NULL = none) */
    void              *on_redirect_data;
    int                redirects_done;
    char               original_url[KL_URL_MAX]; /* for cross-origin checks */
    char               current_url[KL_URL_MAX];
    char               current_method[16];

    /* Completion */
    KlHttpRedirectDoneFn   on_done;
    void              *user_data;
    KlError            error;

    /* A hop's client can complete inside its own start call (an error it could not defer). That
     * completion is held until start_next_request has recorded the client in inner, so on_done
     * never runs, and so never frees rc, under start_next_request's feet. */
    int                starting;
    int                done_pending;
};

/* ── Static helpers ──────────────────────────────────────────────── */

static int is_redirect(int status)
{
    return status == 301 || status == 302 || status == 303 ||
           status == 307 || status == 308;
}

static int method_changes_to_get(int status, const char *method)
{
    if (status == 307 || status == 308)
        return 0;
    /* 301, 302, 303: POST/PUT/PATCH → GET */
    if (status == 303) {
        /* 303: any non-GET/HEAD → GET */
        if (kl_ascii_strcasecmp(method, "GET") != 0 && kl_ascii_strcasecmp(method, "HEAD") != 0)
            return 1;
        return 0;
    }
    /* 301, 302: POST/PUT/PATCH → GET */
    if (kl_ascii_strcasecmp(method, "POST") == 0 ||
        kl_ascii_strcasecmp(method, "PUT") == 0 ||
        kl_ascii_strcasecmp(method, "PATCH") == 0)
        return 1;
    return 0;
}

static int is_cross_origin(const KlUrl *a, const KlUrl *b)
{
    if (a->is_https != b->is_https)
        return 1;
    /* An AF_UNIX URL has no host and no port: its socket path is its origin. Two different
     * sockets are two different servers. */
    if (a->is_unix != b->is_unix)
        return 1;
    if (a->is_unix)
        return strcmp(a->unix_path, b->unix_path) != 0;
    if (a->port != b->port)
        return 1;
    if (a->host_len != b->host_len)
        return 1;
    /* Equal lengths; if both are empty (degenerate/relative URL) the hosts may be
     * NULL, and passing NULL to kl_ascii_strncasecmp(declared nonnull) is UB even at
     * length 0. Two empty hosts are the same origin by host. */
    if (a->host_len == 0)
        return 0;
    if (kl_ascii_strncasecmp(a->host, b->host, a->host_len) != 0)
        return 1;
    return 0;
}

static const char *find_location(const KlHttpClientResponse *resp)
{
    for (int i = 0; i < resp->num_headers; i++) {
        if (kl_ascii_strcasecmp(resp->headers[i].name, "Location") == 0)
            return resp->headers[i].value;
    }
    return NULL;
}

static int should_drop_header(const char *name, int body_dropped, int cross_origin)
{
    /* Host is always regenerated by the client from the URL */
    if (kl_ascii_strcasecmp(name, "Host") == 0)
        return 1;
    /* Drop credentials on cross-origin: the new host must not receive what the caller meant for the
     * original one (the origin's Authorization and Cookie, and the proxy's Proxy-Authorization). */
    if (cross_origin && (kl_ascii_strcasecmp(name, "Authorization") == 0 ||
                         kl_ascii_strcasecmp(name, "Cookie") == 0 ||
                         kl_ascii_strcasecmp(name, "Proxy-Authorization") == 0))
        return 1;
    /* Drop body-related headers when body is dropped */
    if (body_dropped) {
        if (kl_ascii_strcasecmp(name, "Content-Type") == 0 ||
            kl_ascii_strcasecmp(name, "Content-Length") == 0 ||
            kl_ascii_strcasecmp(name, "Transfer-Encoding") == 0)
            return 1;
    }
    return 0;
}

/* ── Sync implementation ─────────────────────────────────────────── */

static int do_sync_request(KlHttpClientPool *pool, KlAllocator *alloc,
                           const KlHttpClientConfig *cfg,
                           const KlHttpRedirectConfig *redir,
                           const char *method, const char *url,
                           const KlHttpClientHeader *headers, int num_headers,
                           const char *body, size_t body_len,
                           KlHttpClientResponse *resp)
{
    if (!kl_allocator_ops_valid(alloc) || !method || !url || !resp)
        return -1;

    int max_redir = (redir && redir->max_redirects > 0)
                        ? redir->max_redirects
                        : KL_HTTP_REDIRECT_DEFAULT_MAX;

    char cur_url[KL_URL_MAX];
    char cur_method[16];

    size_t url_len = strlen(url);
    if (url_len >= sizeof(cur_url))
        return -1;
    memcpy(cur_url, url, url_len + 1);

    size_t mlen = strlen(method);
    if (mlen >= sizeof(cur_method))
        return -1;
    memcpy(cur_method, method, mlen + 1);

    const char *cur_body = body;
    size_t cur_body_len = body_len;

    for (int i = 0; i <= max_redir; i++) {
        /* Build filtered header array on stack */
        KlHttpClientHeader filtered[KL_HTTP_CLIENT_MAX_REQ_HEADERS];
        int nfiltered = 0;

        /* Determine if body is present for this hop */
        int body_dropped = (cur_body == NULL || cur_body_len == 0);

        /* For first request, no cross-origin check */
        int cross_origin = 0;
        if (i > 0) {
            /* Parse current and original to check cross-origin */
            KlUrl prev_parsed, cur_parsed;
            if (kl_url_parse(url, &prev_parsed) == 0 &&
                kl_url_parse(cur_url, &cur_parsed) == 0) {
                cross_origin = is_cross_origin(&prev_parsed, &cur_parsed);
            }
        }

        for (int h = 0; h < num_headers && nfiltered < KL_HTTP_CLIENT_MAX_REQ_HEADERS; h++) {
            if (!should_drop_header(headers[h].name, body_dropped, cross_origin)) {
                filtered[nfiltered++] = headers[h];
            }
        }

        int rc;
        if (pool) {
            rc = kl_http_client_request_pooled(pool, alloc, cfg, cur_method, cur_url,
                                          filtered, nfiltered,
                                          cur_body, cur_body_len, resp);
        } else {
            rc = kl_http_client_request(alloc, cfg, cur_method, cur_url,
                                   filtered, nfiltered,
                                   cur_body, cur_body_len, resp);
        }

        if (rc != 0)
            return -1;

        /* Not a redirect: return final response */
        if (!is_redirect(resp->status))
            return 0;

        /* Find Location header */
        const char *location = find_location(resp);
        if (!location) {
            /* No Location header: return the 3xx response as-is */
            return 0;
        }

        /* Resolve redirect URL */
        char next_url[KL_URL_MAX];
        if (kl_url_resolve(cur_url, location, next_url, sizeof(next_url)) != 0) {
            kl_http_client_response_free(resp);
            resp->error = KL_ERR_URL;
            return -1;
        }

        /* The caller's per-hop policy, before anything is sent there. */
        if (redir && redir->on_redirect &&
            redir->on_redirect(next_url, redir->on_redirect_data) != 0) {
            kl_http_client_response_free(resp);
            memset(resp, 0, sizeof(*resp));
            resp->error = KL_ERR_REDIRECT_REFUSED;
            return -1;
        }

        /* Method transformation */
        if (method_changes_to_get(resp->status, cur_method)) {
            memcpy(cur_method, "GET", 4);
            cur_body = NULL;
            cur_body_len = 0;
        }

        /* Free intermediate response */
        kl_http_client_response_free(resp);

        /* Advance */
        size_t nlen = strlen(next_url);
        if (nlen >= sizeof(cur_url)) {
            /* Zero the struct before setting error: kl_http_client_response_free
             * above invalidated headers/body/num_headers; a caller that
             * inspects them after seeing error != 0 (perfectly reasonable)
             * would hit UAF.  Match the sibling pattern at line ~220
             * (KL_ERR_REDIRECT_LOOP). */
            memset(resp, 0, sizeof(*resp));
            resp->error = KL_ERR_URL;
            return -1;
        }
        memcpy(cur_url, next_url, nlen + 1);
    }

    /* More than max_redirects hops attempted (the loop above runs
     * `max_redir + 1` iterations total: the initial request plus
     * `max_redir` redirect chases). */
    memset(resp, 0, sizeof(*resp));
    resp->error = KL_ERR_REDIRECT_LOOP;
    return -1;
}

int kl_http_redirect_request(KlAllocator *alloc, const KlHttpClientConfig *cfg,
                        const KlHttpRedirectConfig *redir,
                        const char *method, const char *url,
                        const KlHttpClientHeader *headers, int num_headers,
                        const char *body, size_t body_len,
                        KlHttpClientResponse *resp)
{
    return do_sync_request(NULL, alloc, cfg, redir, method, url,
                           headers, num_headers, body, body_len, resp);
}

int kl_http_redirect_request_pooled(KlHttpClientPool *pool,
                               KlAllocator *alloc, const KlHttpClientConfig *cfg,
                               const KlHttpRedirectConfig *redir,
                               const char *method, const char *url,
                               const KlHttpClientHeader *headers, int num_headers,
                               const char *body, size_t body_len,
                               KlHttpClientResponse *resp)
{
    if (!pool)
        return -1;
    return do_sync_request(pool, alloc, cfg, redir, method, url,
                           headers, num_headers, body, body_len, resp);
}

/* ── Async helpers ───────────────────────────────────────────────── */

static KlHttpRedirectClient *alloc_redirect_client(KlAllocator *alloc,
                                               KlEventCtx *ev_ctx,
                                               const KlHttpClientConfig *cfg,
                                               KlHttpClientPool *pool,
                                               const KlHttpRedirectConfig *redir,
                                               const char *method,
                                               const char *url,
                                               const KlHttpClientHeader *headers,
                                               int num_headers,
                                               const char *body, size_t body_len,
                                               KlHttpRedirectDoneFn on_done,
                                               void *user_data)
{
    KlHttpRedirectClient *rc = kl_malloc(alloc, sizeof(KlHttpRedirectClient));
    if (!rc)
        return NULL;
    memset(rc, 0, sizeof(*rc));

    rc->alloc = alloc;
    rc->ev_ctx = ev_ctx;
    if (cfg) {
        rc->cfg_copy = *cfg;
        rc->cfg = &rc->cfg_copy;
    } else {
        rc->cfg = NULL;
    }
    rc->pool = pool;
    rc->on_done = on_done;
    rc->user_data = user_data;
    rc->max_redirects = (redir && redir->max_redirects > 0)
                            ? redir->max_redirects
                            : KL_HTTP_REDIRECT_DEFAULT_MAX;
    rc->on_redirect      = redir ? redir->on_redirect : NULL;
    rc->on_redirect_data = redir ? redir->on_redirect_data : NULL;

    /* Copy method */
    size_t mlen = strlen(method);
    if (mlen >= sizeof(rc->current_method)) {
        kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
        return NULL;
    }
    memcpy(rc->current_method, method, mlen + 1);

    /* Copy URL (both original and current) */
    size_t ulen = strlen(url);
    if (ulen >= sizeof(rc->current_url)) {
        kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
        return NULL;
    }
    memcpy(rc->current_url, url, ulen + 1);
    memcpy(rc->original_url, url, ulen + 1);

    /* Deep-copy headers */
    if (num_headers > 0 && headers) {
        rc->headers = kl_malloc(alloc, (size_t)num_headers * sizeof(KlHttpClientHeader));
        if (!rc->headers) {
            kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
            return NULL;
        }
        for (int i = 0; i < num_headers; i++) {
            size_t nlen = strlen(headers[i].name) + 1;
            size_t vlen = strlen(headers[i].value) + 1;
            char *n = kl_malloc(alloc, nlen);
            char *v = kl_malloc(alloc, vlen);
            if (!n || !v) {
                if (n) kl_free(alloc, n, nlen);
                if (v) kl_free(alloc, v, vlen);
                /* Free already-copied headers */
                for (int j = 0; j < i; j++) {
                    kl_free(alloc, (char *)rc->headers[j].name,
                            strlen(rc->headers[j].name) + 1);
                    kl_free(alloc, (char *)rc->headers[j].value,
                            strlen(rc->headers[j].value) + 1);
                }
                kl_free(alloc, rc->headers,
                        (size_t)num_headers * sizeof(KlHttpClientHeader));
                kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
                return NULL;
            }
            memcpy(n, headers[i].name, nlen);
            memcpy(v, headers[i].value, vlen);
            rc->headers[i].name = n;
            rc->headers[i].value = v;
        }
        rc->num_headers = num_headers;
    }

    /* Deep-copy body */
    if (body && body_len > 0) {
        rc->body = kl_malloc(alloc, body_len);
        if (!rc->body) {
            /* Free headers */
            for (int i = 0; i < rc->num_headers; i++) {
                kl_free(alloc, (char *)rc->headers[i].name,
                        strlen(rc->headers[i].name) + 1);
                kl_free(alloc, (char *)rc->headers[i].value,
                        strlen(rc->headers[i].value) + 1);
            }
            if (rc->headers)
                kl_free(alloc, rc->headers,
                        (size_t)rc->num_headers * sizeof(KlHttpClientHeader));
            kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
            return NULL;
        }
        memcpy(rc->body, body, body_len);
        rc->body_len = body_len;
    }

    return rc;
}

static void internal_on_done(KlHttpClient *client, void *user_data);

static int start_next_request(KlHttpRedirectClient *rc, int first)
{
    /* Build filtered headers */
    KlHttpClientHeader filtered[KL_HTTP_CLIENT_MAX_REQ_HEADERS];
    int nfiltered = 0;
    int body_dropped = (rc->body == NULL || rc->body_len == 0);

    /* Cross-origin: compare current target against original URL */
    int cross_origin = 0;
    if (rc->redirects_done > 0) {
        KlUrl orig_parsed, cur_parsed;
        if (kl_url_parse(rc->original_url, &orig_parsed) == 0 &&
            kl_url_parse(rc->current_url, &cur_parsed) == 0) {
            cross_origin = is_cross_origin(&orig_parsed, &cur_parsed);
        }
    }

    for (int h = 0; h < rc->num_headers && nfiltered < KL_HTTP_CLIENT_MAX_REQ_HEADERS; h++) {
        if (!should_drop_header(rc->headers[h].name, body_dropped, cross_origin))
            filtered[nfiltered++] = rc->headers[h];
    }

    KlHttpClient *inner;
    rc->starting = 1;
    rc->done_pending = 0;
    if (rc->pool) {
        inner = kl_http_client_start_pooled(rc->pool, rc->ev_ctx, rc->alloc, rc->cfg,
                                       rc->current_method, rc->current_url,
                                       filtered, nfiltered,
                                       rc->body, rc->body_len,
                                       internal_on_done, rc);
    } else {
        inner = kl_http_client_start(rc->ev_ctx, rc->alloc, rc->cfg,
                                rc->current_method, rc->current_url,
                                filtered, nfiltered,
                                rc->body, rc->body_len,
                                internal_on_done, rc);
    }

    rc->starting = 0;
    if (!inner)
        return -1;

    rc->inner = inner;
    if (rc->done_pending) {                  /* it completed inside its start */
        rc->done_pending = 0;
        if (first) {                         /* the caller has no handle yet: fail the start */
            kl_http_client_free(inner);      /* (NULL, no callback), as the plain client does */
            rc->inner = NULL;
            return -1;
        }
        internal_on_done(inner, rc);         /* a later hop: report it; may free rc, so nothing */
    }                                        /* touches rc after this */
    return 0;
}

static void internal_on_done(KlHttpClient *client, void *user_data)
{
    KlHttpRedirectClient *rc = user_data;
    (void)client;
    if (rc->starting) {                      /* inside start_next_request: rc->inner not set yet */
        rc->done_pending = 1;
        return;
    }

    /* Error from inner client */
    if (kl_http_client_error(rc->inner) != 0) {
        rc->error = kl_http_client_last_error(rc->inner);
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    const KlHttpClientResponse *resp = kl_http_client_response(rc->inner);
    if (!resp) {
        rc->error = KL_ERR_IO;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* Not a redirect: we're done, final response */
    if (!is_redirect(resp->status)) {
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* Check redirect limit */
    if (rc->redirects_done >= rc->max_redirects) {
        rc->error = KL_ERR_REDIRECT_LOOP;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* Find Location */
    const char *location = find_location(resp);
    if (!location) {
        /* No Location: return the 3xx as final */
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* Resolve URL */
    char next_url[KL_URL_MAX];
    if (kl_url_resolve(rc->current_url, location, next_url, sizeof(next_url)) != 0) {
        rc->error = KL_ERR_URL;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* The caller's per-hop policy, before anything is sent there. The 3xx
     * stays on the inner client but is not the final response: the request
     * ends refused (kl_http_redirect_response returns NULL on error). */
    if (rc->on_redirect &&
        rc->on_redirect(next_url, rc->on_redirect_data) != 0) {
        rc->error = KL_ERR_REDIRECT_REFUSED;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }

    /* Method transformation */
    if (method_changes_to_get(resp->status, rc->current_method)) {
        memcpy(rc->current_method, "GET", 4);
        /* Drop body */
        if (rc->body) {
            kl_free(rc->alloc, rc->body, rc->body_len);
            rc->body = NULL;
            rc->body_len = 0;
        }
    }

    /* Update URL */
    size_t nlen = strlen(next_url);
    if (nlen >= sizeof(rc->current_url)) {
        rc->error = KL_ERR_URL;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
        return;
    }
    memcpy(rc->current_url, next_url, nlen + 1);

    /* Free the intermediate client (and its response) */
    kl_http_client_free(rc->inner);
    rc->inner = NULL;

    rc->redirects_done++;

    /* Start the next request */
    if (start_next_request(rc, 0) != 0) {
        rc->error = KL_ERR_IO;
        if (rc->on_done)
            rc->on_done(rc, rc->user_data);
    }
}

/* ── Async public API ────────────────────────────────────────────── */

KlHttpRedirectClient *kl_http_redirect_start(KlEventCtx *ev_ctx, KlAllocator *alloc,
                                    const KlHttpClientConfig *cfg,
                                    const KlHttpRedirectConfig *redir,
                                    const char *method, const char *url,
                                    const KlHttpClientHeader *headers, int num_headers,
                                    const char *body, size_t body_len,
                                    KlHttpRedirectDoneFn on_done, void *user_data)
{
    if (!ev_ctx || !kl_allocator_ops_valid(alloc) || !method || !url)
        return NULL;

    KlHttpRedirectClient *rc = alloc_redirect_client(alloc, ev_ctx, cfg, NULL, redir,
                                                 method, url, headers, num_headers,
                                                 body, body_len, on_done, user_data);
    if (!rc)
        return NULL;

    if (start_next_request(rc, 1) != 0) {
        kl_http_redirect_free(rc);
        return NULL;
    }

    return rc;
}

KlHttpRedirectClient *kl_http_redirect_start_pooled(KlHttpClientPool *pool,
                                           KlEventCtx *ev_ctx, KlAllocator *alloc,
                                           const KlHttpClientConfig *cfg,
                                           const KlHttpRedirectConfig *redir,
                                           const char *method, const char *url,
                                           const KlHttpClientHeader *headers, int num_headers,
                                           const char *body, size_t body_len,
                                           KlHttpRedirectDoneFn on_done, void *user_data)
{
    if (!pool || !ev_ctx || !kl_allocator_ops_valid(alloc) || !method || !url)
        return NULL;

    KlHttpRedirectClient *rc = alloc_redirect_client(alloc, ev_ctx, cfg, pool, redir,
                                                 method, url, headers, num_headers,
                                                 body, body_len, on_done, user_data);
    if (!rc)
        return NULL;

    if (start_next_request(rc, 1) != 0) {
        kl_http_redirect_free(rc);
        return NULL;
    }

    return rc;
}

const KlHttpClientResponse *kl_http_redirect_response(const KlHttpRedirectClient *rc)
{
    if (!rc || !rc->inner)
        return NULL;
    if (rc->error != KL_ERR_NONE)
        return NULL;
    return kl_http_client_response(rc->inner);
}

int kl_http_redirect_error(const KlHttpRedirectClient *rc)
{
    if (!rc)
        return -1;
    if (rc->error != KL_ERR_NONE)
        return -1;
    if (rc->inner)
        return kl_http_client_error(rc->inner);
    return -1;
}

KlError kl_http_redirect_last_error(const KlHttpRedirectClient *rc)
{
    if (!rc)
        return KL_ERR_INVALID_ARG;
    if (rc->error != KL_ERR_NONE)
        return rc->error;
    if (rc->inner)
        return kl_http_client_last_error(rc->inner);
    return KL_ERR_NONE;
}

void kl_http_redirect_cancel(KlHttpRedirectClient *rc)
{
    if (!rc)
        return;
    if (rc->inner) {
        kl_http_client_cancel(rc->inner);
    }
    if (rc->error == KL_ERR_NONE)
        rc->error = KL_ERR_IO;
}

void kl_http_redirect_free(KlHttpRedirectClient *rc)
{
    if (!rc)
        return;

    KlAllocator *alloc = rc->alloc;

    if (rc->inner) {
        kl_http_client_free(rc->inner);
        rc->inner = NULL;
    }

    /* Free deep-copied headers */
    for (int i = 0; i < rc->num_headers; i++) {
        if (rc->headers[i].name)
            kl_free(alloc, (char *)rc->headers[i].name,
                    strlen(rc->headers[i].name) + 1);
        if (rc->headers[i].value)
            kl_free(alloc, (char *)rc->headers[i].value,
                    strlen(rc->headers[i].value) + 1);
    }
    if (rc->headers)
        kl_free(alloc, rc->headers,
                (size_t)rc->num_headers * sizeof(KlHttpClientHeader));

    /* Free copied body */
    if (rc->body)
        kl_free(alloc, rc->body, rc->body_len);

    kl_free(alloc, rc, sizeof(KlHttpRedirectClient));
}
